name: Build Kernel (thyme MIUI + SukiSU, no OIS)

on:
  workflow_dispatch:
  push:
    branches: [ "android15-lineage22-mod" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: android15-lineage22-mod
          fetch-depth: 1

      - name: Install deps & cross compilers
        run: |
          sudo apt update
          sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 clang lld binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Download Proton Clang (for headers & lib)
        run: |
          mkdir -p ~/proton-clang && cd ~/proton-clang
          wget -q https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
          unzip -q 20210522.zip
          # 删除老古董 ld，让系统 ld 接替
          rm -f ~/proton-clang/proton-clang-20210522/bin/ld
          rm -f ~/proton-clang/proton-clang-20210522/bin/aarch64-linux-gnu-ld
          rm -f ~/proton-clang/proton-clang-20210522/bin/arm-linux-gnueabi-ld

      - name: Disable OIS driver + use AOSP camera
        run: |
          sed -i '/cam_ois\//s/^/#/' techpack/camera/drivers/cam_sensor_module/Makefile
          sed -i '/cam_ois\//s/^/#/' techpack/camera-xiaomi/drivers/cam_sensor_module/Makefile
          sed -i '/CONFIG_TECHPACK_CAMERA_XIAOMI/d' arch/arm64/configs/thyme_defconfig

      - name: Build kernel
        run: |
          # 系统已安装的 aarch64-linux-gnu-ld 在 /usr/bin，工具链 PATH 优先
          bash build.sh thyme ksu

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_MIUI_thyme_SukiSU-SUSFS_noOIS
          path: ./Kernel_MIUI_thyme_*.zip
          compression-level: 0
